### ISSUE TITLE
update the price 

### ISSUE THREAD

**Issue by prodigeomid** [osamaasifoak/flutter_cart#13]
Hello i want to update the price in my cart how i can do ?

**Comment by dassimanuel000** [comment]
ME TOO

**Comment by osamaasifoak** [comment]
Hi @dassimanuel000 @prodigeomid, do you want to update the price of specific item? Can you please elaborate it more? So, I can understand it better thanks.

**Comment by prodigeomid** [comment]
@osamaasifoak, yes i want to modify the price of specific items who is already on cart, thanks you.

**Comment by prodigeomid** [comment]
@osamaasifoak any update sir ?

**Comment by osamaasifoak** [comment]
@prodigeomid, why not remove that item from the cart and add a new one with the updated pricing?

**Comment by prodigeomid** [comment]
@osamaasifoak because i want to add discount but not when the user add the user, i want to add the discount when the cart is already on item cart is better

**Comment by osamaasifoak** [comment]
@prodigeomid Alright, if you want to apply discount on a specific item. You can use a function named applyDiscount in which you can simply just pass the productId, product variant and discount it will update the price of an item. I'm still here if you need any help thanks🙂
