### ISSUE TITLE
retrieve cart items

### ISSUE THREAD

**Issue by utpal4job** [osamaasifoak/flutter_cart#5]
Hello, please help me how to retrieve cart items.

Regards.

**Comment by Scienticious** [comment]
Hi, 
@utpal4job , Sorry I didn't respond ,because I was a little bit busy.


I will update the documentation and the package tomorrow

**Comment by utpal4job** [comment]
> Hi,
> @utpal4job , Sorry I didn't respond ,because I was a little bit busy.
> 
> I will update the documentation and the package tomorrow

ok, waiting here...

**Comment by Scienticious** [comment]
cart item is saved in 

> 
> 
> > Hi,
> > @utpal4job , Sorry I didn't respond ,because I was a little bit busy.
> > I will update the documentation and the package tomorrow
> 
> ok, waiting here...
List<CartItem> get cartItem => _cartItemList;

**Comment by Scienticious** [comment]
@utpal4job  sorry for being late,
you can get the item by    
"getSpecificItemFromCart(cartId)" method.

We have updated this package to null safety ,
So please use the latest version.
And if you found any confusion regarding this package so feel free to contact us
