### ISSUE TITLE
using "getSpecificItemFromCart(cartId)" method we will get only one item from cart

### ISSUE THREAD

**Issue by utpal4job** [osamaasifoak/flutter_cart#7]
Hello, using "getSpecificItemFromCart(cartId)" method we will get only one item from cart, we need all the items from cart.

Regards.

**Comment by Scienticious** [comment]
you can access all items in with your flutterCart object like this ,
  var flutterCart = FlutterCart();
flutterCart.cartItem;

Basically, cartItem is a private list that contains all your  cart items.

we have uploaded the working example in the Example named folder , you can run and check the working as well.

Fell free to share your feedback .

Regards

**Comment by utpal4job** [comment]
Hello, thanks for your reply. I will let you know if any issues appear.

Regards.

**Comment by Scienticious** [comment]
Further, we will also update the package and the example sooner,
Please star our project and share with your friends also.

Best Regards.

**Comment by utpal4job** [comment]
Yes, I will share for sure.

Regards.

**Comment by Scienticious** [comment]
> 
> 
> you can access all items in with your flutterCart object like this ,
> var flutterCart = FlutterCart();
> flutterCart.cartItem;
> 
> Basically, cartItem is a private list that contains all your cart items.
> 
> we have uploaded the working example in the Example named folder , you can run and check the working as well.
> 
> Fell free to share your feedback .
> 
> Regards

@utpal4job your issue will be resolved if you follow the above guidelines,
Currently, I am Closing this issue. 

Thanks
