### ISSUE TITLE
offline support

### ISSUE THREAD

**Issue by iamirzashowvik** [osamaasifoak/flutter_cart#8]
make it offline support or i make it own?will i make a pull request?

**Comment by Scienticious** [comment]
It already has an offline support

**Comment by iamirzashowvik** [comment]
> It already has an offline support

Where bro? Can i have this link?

**Comment by Scienticious** [comment]
Currently, we are using this cart in provider or any state management variable,
You may raise a pull request regarding the offline support

**Comment by iamirzashowvik** [comment]
Sir i made it already.will i make a pull request?

**Comment by osamaasifoak** [comment]
@iamirzashowvik Kindly make a pull request.

**Comment by Scienticious** [comment]
@iamirzashowvik you may raise a pull request.

**Comment by Scienticious** [comment]
Hi @iamirzashowvik , I have checked that you have implmented the offline functionality, please raise a pull request so we can discuss and merge you PR.
If you have any difficulty feel free to ask it.
Thanks
